// Anything that can describe its own routing, whatever shape it is. A root schema has to be a
// protocol requirement rather than a macro overload, because a function generic over `Value` --
// `partials(of:from:)` -- cannot pick an overload on its behalf. Kept separate from
// `StreamParseableObject` so the constrained `_streamFieldRoute` cannot route a `String` field.
public protocol StreamParseableRoot: StreamInitializable {
  static var streamSchema: StreamSchema { get }

  #if !hasFeature(Embedded)
    /// Direct stored key paths used to validate field observation. Generated by `@StreamParseable`.
    ///
    /// Custom roots must list every stored member, including members ignored by their schema,
    /// so observation can reject ambiguous overlapping storage. Do not include computed or
    /// nested paths. The default empty list disables field observation.
    static var streamObservationFields: [PartialKeyPath<Self>] { get }
  #endif

  /// Appends a run of numbers to a `StreamArray<Self>` in one call, or `nil` when `Self` is not
  /// a number. Supplied for every ``StreamNumberConvertible`` type; the array schema carries it
  /// as ``StreamSchema/appendNumbers`` so `PartialSink` can take a batch without routing each
  /// number through a frame.
  static var _streamArrayNumberAppender:
    (@Sendable (UnsafeMutableRawPointer, borrowing StreamEventBatch, Int, Int) -> Int)? { get }

  /// The schema this type is written through as an array element, and the value the array opens
  /// the element's slot with. ``StreamSchema/Usage/arrayElement``.
  ///
  /// These differ from ``streamSchema`` and ``StreamInitializable/streamInitialValue()`` only for
  /// `Optional`: an array owns the slot it hands out and can open it already materialised, so an
  /// optional element never checks for `nil` before a write, where a bare optional *root* must.
  /// Worth 2.4x on `[Int?]` (NEW_ARCHITECTURE.md, "The optional seam"). The defaults are the root
  /// forms, so every type but `Optional` conforms without saying anything.
  static var streamArrayElementSchema: StreamSchema { get }

  /// - SeeAlso: ``streamArrayElementSchema``
  static func streamInitialArrayElement() -> Self

  /// The schema this type is written through as a dictionary value, and the value the dictionary
  /// opens the value's slot with. ``StreamSchema/Usage/dictionaryValue``.
  ///
  /// A dictionary owns the slot it opens under a key exactly as an array owns an element's, so
  /// the defaults are the array-element forms, which is what `Optional` relies on.
  static var streamDictionaryValueSchema: StreamSchema { get }

  /// - SeeAlso: ``streamDictionaryValueSchema``
  static func streamInitialDictionaryValue() -> Self

  /// What a whole-value `null` writes into a member of this type, or `nil` for a type that has
  /// no null of its own, whose optional member is cleared instead.
  ///
  /// The macro decides this from a member's declared type (`streamApplyNull`'s overloads) except
  /// where that type is a generic parameter's `Partial`, which the overloads cannot see through.
  /// Defaults to ``StreamNullable/streamNullValue()`` for a nullable type, so `Box<Int?>` takes a
  /// `null` as `.some(nil)` -- a present null, as `Codable` reads it -- where a concrete `Int?`
  /// member, whose optionality is written, has only the one `nil`.
  static var _streamNullValue: Self? { get }

  /// Whether a container opens a slot of this type by constructing ``streamInitialValue()``
  /// rather than copying the template its schema hoisted.
  ///
  /// True for the `Partial` the macro generates for a generic struct, and `false` for everything
  /// else. A bound generic struct's copy is not emitted field by field: it fetches the type's
  /// metadata and calls its value witness, which walks the fields through metadata too. Measured
  /// on the matched Twitter model, one generic level cost 1.5% per element opened that way, while
  /// constructing is the specialised `init`'s inline stores. A concrete `Partial` keeps the
  /// template: its copy is inline, and its `streamInitialValue()` is itself a copy of one.
  static var _streamOpensByConstruction: Bool { get }

  /// A borrowed window onto the value, for reading part of it without copying the whole.
  ///
  /// Defaults to ``StreamPointerView``, which is what a scalar wants. A type with members worth
  /// reading one at a time overrides it with a projection whose accessors copy only what they return.
  ///
  /// With the `LifetimeView` trait this is `~Escapable`, so "must outlive the view" on
  /// ``streamView(_:)`` is compiler-checked rather than merely documented. Without the trait,
  /// views are escapable unsafe pointer projections and callers must uphold that invariant.
  /// There is deliberately no `= Self` fallback because the macro generates member projections.
#if LifetimeView
  associatedtype View: ~Copyable, ~Escapable
#else
  associatedtype View: ~Copyable
#endif

  /// Builds a view over a value at `storage`.
  ///
  /// The lifetime dependency on `storage` ties the returned view's borrow-checked scope to the
  /// call site: the pointer itself carries no lifetime of its own, but the dependency still
  /// forces callers through an API shape (like a `withView`-style closure) that cannot let the
  /// view outlive the call that produced it.
#if LifetimeView
  @_lifetime(borrow storage)
#else
  @unsafe
#endif
  static func streamView(_ storage: UnsafeMutableRawPointer) -> View
}

extension StreamParseableRoot {
  @inlinable
  public static var streamArrayElementSchema: StreamSchema { Self.streamSchema }

  @inlinable
  public static func streamInitialArrayElement() -> Self { Self.streamInitialValue() }

  @inlinable
  public static var streamDictionaryValueSchema: StreamSchema { Self.streamArrayElementSchema }

  @inlinable
  public static func streamInitialDictionaryValue() -> Self { Self.streamInitialArrayElement() }

  @inlinable
  public static var _streamNullValue: Self? { nil }

  @inlinable
  public static var _streamOpensByConstruction: Bool { false }
}

extension StreamParseableRoot where Self: StreamNullable {
  @inlinable
  public static var _streamNullValue: Self? { Self.streamNullValue() }
}

extension StreamParseableRoot where View == StreamPointerView<Self> {
  // A correct snapshot without a recursive rebuild: every container the parser writes into holds
  // its open element in an inline slot, so a copy shares only storage that is sealed and never
  // written again, and the open element's own buffers copy on write at the next append.
#if LifetimeView
  @_lifetime(borrow storage)
#else
  @unsafe
#endif
  public static func streamView(_ storage: UnsafeMutableRawPointer) -> StreamPointerView<Self> {
    StreamPointerView(storage)
  }
}

/// A partial that can receive an incoming container when stored as a field.
///
/// The entry operation lives on the resolved partial type, so aliases and generic wrappers do not
/// need to expose their shape in source syntax. A partial whose storage is described directly by
/// its ``StreamParseableRoot/streamSchema`` can use the default implementation.
public protocol StreamContainerPartial: StreamParseableRoot {
  /// The schema a container entry installs on the frame it pushes when this type is a declared
  /// member of an object. ``StreamSchema/Usage/objectMember``.
  ///
  /// Separated from the frame so a caller can resolve it once and store it: `streamSchema` is a
  /// computed property on every generic partial, so reading it per entry allocates per container
  /// occurrence and leaves the entry's frame as the schema's only owner. The macro resolves it
  /// once per schema build, and the parent's field table owns the result.
  static var streamObjectMemberSchema: StreamSchema { get }

  /// Makes the storage of a member of this type ready for ``streamObjectMemberSchema`` to write
  /// through, before the sink pushes a frame over it; runs once per container occurrence. `nil`
  /// for a type whose storage is its own value, which is every type but `Optional`, which
  /// materialises its payload here. The table stores it as the member's `prepare`.
  static var _streamObjectMemberPrepare: StreamFieldPrepare? { get }
}

extension StreamContainerPartial {
  @inlinable
  public static var streamObjectMemberSchema: StreamSchema {
    Self.streamSchema
  }

  @inlinable
  public static var _streamObjectMemberPrepare: StreamFieldPrepare? { nil }
}

// Refines `StreamContainerPartial` so a nested object field's schema is hoisted by its parent
// exactly as a container field's is. Reading `T.streamSchema` per occurrence builds a fresh schema
// for any hand-written conformance, leaving the frame as its only owner — invisible while a frame
// retains its schema, fatal now that a frame borrows it.
public protocol StreamParseableObject: StreamContainerPartial {}

// MARK: - Scalar roots

extension StreamParseableRoot where Self: StreamStringConvertible {
  public static var streamSchema: StreamSchema { _streamStringSchema(Self.self) }
}

extension StreamParseableRoot where Self: StreamNumberConvertible {
  public static var streamSchema: StreamSchema { _streamNumberSchema(Self.self) }
}

extension StreamParseableRoot where Self: StreamBooleanConvertible {
  public static var streamSchema: StreamSchema { _streamBooleanSchema(Self.self) }
}

#if !hasFeature(Embedded)
  extension StreamParseableRoot {
    public static var streamObservationFields: [PartialKeyPath<Self>] { [] }
  }
#endif
